#! /bin/sh

git add .
echo "Enter Commit Message: $name"
read commitMessage
echo "Enter the new tag "
read newTag
git commit -m "$commitMessage $snewTag"
echo "Current Tag is : " $(git describe --abbrev=0 --tags)
git tag '$newTag'
git push --

echo "finished new tag is $snewTag"

